# Site settings
title: Nauman Umer - We talk with machines
email: u.nauman@outlook.com
url: "http://naumanumer.github.io" # the base hostname & protocol for your site
github_username:  naumanumer
movieFormUrl: https://staticman.net/api/v1/entries/5622d244c4bf944a1a3e3001
future: true
timezone: Asia/Karachi
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

# Staticman
staticman:
 allowedFields: ['name', 'title', 'description', 'rating']
 branch: gh-pages
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
 requiredFields: ['name', 'title', 'description', 'rating']
