site_name: Entry Test Notes
site_author: 'Nauman Umer'
site_description: 'Entry Test notes for FUNG enrty test prepration'
site_url: "https://nmanumr.github.io/Fung-notes"

theme: 'material'
copyright: 'Written by Nauman Umer'
repo_name: 'nmanumr/Fung-notes'
repo_url: 'https://www.github.com/nmanumr/nmanumr.github.io'
edit_uri: 'blob/master/docs/'
extra:
  disqus: 'naumanumer'


pages:
    - Home: 'index.md'
    - Physics:
        - '01 - Measurements': 'physics/ch01.md'
        - '02 - Vectors': 'physics/ch02.md'
        - '03 - Motion & Force': 'physics/ch03.md'
        - '04 - Work & Energy': 'physics/ch04.md'
        - '05 - Circular Motion': 'physics/ch05.md'
        - '06 - Fluid Dynamics': 'physics/ch06.md'
        - '07 - Oscillations': 'physics/ch07.md'
        - '08 - Waves': 'physics/ch08.md'
        - '09 - Physical Optics': 'physics/ch09.md'
        - '10 - Optical Instruments': 'physics/ch10.md'
        - '11 - Heat and Thermodynamics': 'physics/ch11.md'
        - '12 - Electrostatics': 'physics/ch12.md'
        - '13 - Current Electricity': 'physics/ch13.md'
        - '14 - Electromegnetism': 'physics/ch14.md'
        - '15 - Electromegnetic Induction': 'physics/ch15.md'
        - '16 - Alternating Current': 'physics/ch16.md'
        - '17 - Physics of Solids': 'physics/ch17.md'
        - '18 - Electronics': 'physics/ch18.md'
        - '19 - Dawn of Modern Physics': 'physics/ch19.md'
        - '20 - Atomic Spectra': 'physics/ch20.md'
        - '21 - Nuclear Physics': 'physics/ch21.md'
    - Maths:
        - '01 - Number System': 'maths/ch01.md'
        - '02 - Set, Functions & Groups': 'maths/ch02.md'
        - '03 - Matrices & Determinants': 'maths/ch03.md'
        - '04 - Quadratic Equations': 'maths/ch04.md'
        - '05 - Partial Fraction': 'maths/ch05.md'
        - '06 - Sequence & Series': 'maths/ch06.md'
        - '07 - Permutation, Combination & Probability': 'maths/ch07.md'
        - '08 - Binomial Theorem': 'maths/ch08.md'
        - '09 - Fundamentals of Trigonometry': 'maths/ch09.md'
        - '10 - Trigonometric Identities': 'maths/ch10.md'
        - '11 - Trigonometric Function': 'maths/ch11.md'
        - '12 - Application of Trigonometry': 'maths/ch12.md'
        - '13 - Inverse Trigonometric Functions': 'maths/ch13.md'
        - '14 - Trigonometric Equations': 'maths/ch14.md'
        - '15 - Functions & Limits': 'maths/ch15.md'
        - '16 - Differentiation': 'maths/ch16.md'
        - '17 - Integration': 'maths/ch17.md'
        - '18 - Linear Inequalities': 'maths/ch18.md'
        - '19 - Analytical Geometry': 'maths/ch19.md'
        - '20 - Conic Sections': 'maths/ch20.md'
        - '21 - Vector': 'maths/ch21.md'

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.css'
  - 'css/index.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/contrib/auto-render.min.js'
  - 'js/index.js'
